# Generated by Django 4.1.7 on 2023-03-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='projects.tag'),
        ),
    ]
