# Generated by Django 4.1.7 on 2023-03-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_tag_project_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
