# Generated by Django 4.1.7 on 2023-04-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_title_long_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
