# Generated by Django 4.1.7 on 2023-03-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='', verbose_name='/profile')),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
