# Generated by Django 4.1.7 on 2023-03-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_bio_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bio',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
