# Generated by Django 4.1.7 on 2023-03-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_bio_title_alter_bio_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
