# Generated by Django 4.1.7 on 2023-03-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_bio_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
